### PR TITLE
Cross Compile CMake support

### PR DESCRIPTION
**Pull request by arthurzam**
As with todo list on #22 

I was compiling with mingw-w64 of Arch Linux. I needed to install those applications (latest version):

1. mingw-w64-cmake
2. mingw-w64-ffmpeg
3. mingw-w64-gcc
4. mingw-w64-portaudio
5. mingw-w64-qt5-base

Therefore, I have no idea what happens on old versions of those packages.

Some changes I have done:

- added option to specify LANGUAGES as empty string - same result as with None.
- added CMake script file for DirectX and FileAssociations.
- In FileAssociations I needed to add the UNICODE definition for it compiling. something with converting QString to LCSTR (maybe we should make in code ifndef UNICODE?)
- some more checks for libraries (find zlib for Modplug)
- about OpenGL module: there were some gl functions that I needed to find the appropriate lib file (wasn't specified in pro file). After binary grep in all mingw folder the only one that worked was GLESv2. Please say your thoughts!
- I managed only to compile. I can't use Wine and I don't have Windows to check. So testing if it works is on you. Also can you share with me Window's files list?

On another note - I'm researching now how to install with program all of its dependencies. For example including with PortAudio module the portaudio dll. In case I manage it it will make packaging for Windows easier (I think).

### CODE REVIEW

**Comment by zaps166** [comment]
Thanks!! I'll test it soon :)

> added option to specify LANGUAGES as empty string - same result as with None.

Maybe get rid of None ?

> In FileAssociations I needed to add the UNICODE definition for it compiling. something with converting QString to LCSTR (maybe we should make in code ifndef UNICODE?)

Ok, `qmake` automatically adds this definition AFAIK.

> about OpenGL module: there were some gl functions that I needed to find the appropriate lib file (wasn't specified in pro file). After binary grep in all mingw folder the only one that worked was GLESv2. Please say your thoughts!

Windows itself doesn't support GLES (maybe some drivers supports it, but it is not portable there). ANGLE - forget about it :D. This is something like WINE does DX->GL; ANGLE translates GLESv2 to DirectX. QMPlay2 doesn't support this and it doesn't make any sense. At least you can autodetect (autodetection is already in CMakeLists), but don't force GLESv2 :)

---

Is it possible to choose which libraries will be statically linked and which will be DLLs (like I did in `*.pro` files)?

On Windows it is better to use Qt4 - faster startup, less size, no advantages of Qt5 for QMPlay2. Is it possible to support it also with this PR? If yes (+static libs) I will be able to replace my scripts with `CMake` :)

**Comment by zaps166** [comment]
> Also can you share with me Window's files list?

Yes :smile: (from 32-bit Windows installer):

```sh
$ find QMPlay2
QMPlay2
QMPlay2/lang
QMPlay2/lang/de.qm
QMPlay2/lang/es.qm
QMPlay2/lang/zh.qm
QMPlay2/lang/ru.qm
QMPlay2/lang/fr.qm
QMPlay2/lang/pl.qm
QMPlay2/imageformats
QMPlay2/imageformats/qjpeg4.dll
QMPlay2/imageformats/qgif4.dll
QMPlay2/avformat-57.dll
QMPlay2/QtOpenGL4.dll
QMPlay2/QMPlay2.exe
QMPlay2/avcodec-57.dll
QMPlay2/modules
QMPlay2/modules/AudioFilters.dll
QMPlay2/modules/FFmpeg.dll
QMPlay2/modules/Inputs.dll
QMPlay2/modules/QPainter.dll
QMPlay2/modules/Extensions.dll
QMPlay2/modules/DirectX.dll
QMPlay2/modules/Playlists.dll
QMPlay2/modules/FileAssociation.dll
QMPlay2/modules/Modplug.dll
QMPlay2/modules/Chiptune.dll
QMPlay2/modules/VideoFilters.dll
QMPlay2/modules/AudioCD.dll
QMPlay2/modules/Visualizations.dll
QMPlay2/modules/Subtitles.dll
QMPlay2/modules/PortAudio.dll
QMPlay2/modules/OpenGL2.dll
QMPlay2/libgcc_s_sjlj-1.dll
QMPlay2/QtCore4.dll
QMPlay2/COPYING
QMPlay2/QtGui4.dll
QMPlay2/qmplay2.dll
QMPlay2/avutil-55.dll
QMPlay2/swresample-2.dll
QMPlay2/ssleay32.dll
QMPlay2/swscale-4.dll
QMPlay2/libwinpthread-1.dll
QMPlay2/libeay32.dll
QMPlay2/libstdc++-6.dll
QMPlay2/fonts
QMPlay2/fonts/conf.d
QMPlay2/fonts/conf.d/65-nonlatin.conf
QMPlay2/fonts/conf.d/20-unhint-small-vera.conf
QMPlay2/fonts/conf.d/69-unifont.conf
QMPlay2/fonts/conf.d/49-sansserif.conf
QMPlay2/fonts/conf.d/80-delicious.conf
QMPlay2/fonts/conf.d/90-synthetic.conf
QMPlay2/fonts/conf.d/51-local.conf
QMPlay2/fonts/conf.d/60-latin.conf
QMPlay2/fonts/conf.d/30-metric-aliases.conf
QMPlay2/fonts/conf.d/40-nonlatin.conf
QMPlay2/fonts/conf.d/10-scale-bitmap-fonts.conf
QMPlay2/fonts/conf.d/45-latin.conf
QMPlay2/fonts/conf.d/30-urw-aliases.conf
QMPlay2/fonts/conf.d/65-fonts-persian.conf
QMPlay2/fonts/conf.d/50-user.conf
QMPlay2/fonts/fonts.conf
QMPlay2/zlib1.dll
QMPlay2/ChangeLog
QMPlay2/QtNetwork4.dll
```

64-bit desn't have `QMPlay2/fonts` and has other `libgcc*` library name.

**Comment by zaps166** [comment]
> On another note - I'm researching now how to install with program all of its dependencies.

If it is possible this can introduce a lot of (difficult and messy) code for CMake. This is very easy to do for a bash script. I think that only QMPlay2 should be installed (w/o dependencies and other files like `fontconfig` files).

**Comment by zaps166** [comment]
Sorry for the conflict, I've changed `LANGUAGES` (not tested yet).

**Comment by arthurzam** [comment]
I rebased with your new commit. It's alright.

About the dependencies - I meant only the dll files. But now I guess it won't work properlly. The script way is better. As script we can even scan all of the files and print the dll dependencies.

About Qt4 - I can't compile because of problem of Qt4's isystem and gcc 6 (this is Qt4's fault here). I don't have enough time to compile again all Qt4 with this patch - therefore the testing is on you (in theory it should work properly with the regular -DUSE_QT5=OFF).

About static linking: I have found how to do it. It won't integrate elegantly in the code. CMake has no straightforward flag for switching dynamic/static when placing the libs. What I need to do is something like this:
```
find_library(LIBASS libass.a)
target_link_libraries(${PROJECT_NAME} LIBASS)
```
Maybe it looks okay, but it means we should discard those pkg-config for Windows and MinGW - is it acceptable? I know there is no east pkg-config on Windows itself, but even though it is quite "nice" in cross-compile mingw. I leave the decision on you.

**Comment by zaps166** [comment]
About static linking, portaudio example: "-Wl,-Bstatic ${LIBPORTAUDIO_LIBRARIES} -Wl,-Bdynamic" - is it OK?

**Comment by zaps166** [comment]
One question: how to test it :smiley:, what command is needed?

**Comment by arthurzam** [comment]
Do you have patches Qt4 for MinGW? if yes then continue.
install mingw-w64-cmake
```
mkdir build && cd build
x86_64-w64-mingw32-cmake ../ -DUSE_QT5=OFF
```
(I needed to also add `-DUSE_TAGLIB=OFF` because I don't have it installed on mingw)

**Comment by zaps166** [comment]
> Well, CMake's target_link_libraries doesn't work like this (it will receive ass instead of -lass)

Ok

> install mingw-w64-cmake

Ok, but what about cross-compilation from normal linux cmake not designed for MinGW?

**Comment by arthurzam** [comment]
If you have the appropriate target of cmake with compiler paths (like this mingw-w64-cmake) then it will work. There is no really big differences between the CMake files (all I changed in this PR was Windows support).

**Comment by zaps166** [comment]
Ok, now it mostly works :)

- if I don't have Qt5 on MinGW it detects (probably) Linux Qt5 and tries to use it.
- `Extensions` module shouldn't use DBus for Windows (just like OS X (Darwin)).

**Comment by arthurzam** [comment]
> if I don't have Qt5 on MinGW it detects (probably) Linux Qt5 and tries to use it.

Cross-compiling is very problematic state. IF someone want to try it, they should really check that all dependencies are installed and check (for example using Cmake-gui in advanced mode) that everything is configured properly.

**Comment by zaps166** [comment]
Ok :smile: 

Missing `-UNICODE`, but I'll fix it in C++.

**Comment by zaps166** [comment]
OpenGL module doesn't link. You should follow Qt OpenGL/GLES and link to proper library depends what Qt uses (ANGLE(GLESv2) or native OpenGL). If not GLES, link to `opengl32`.

**Comment by arthurzam** [comment]
Sorry but I don't understand the which use with which.

**Comment by zaps166** [comment]
I have problem with `AudioCD` module, because I've got only static libs and it needs additional libraries to link. The best idea will be to specify manual linker libraries in CMake as an option (discarding auto-detected libraries)  :)

Is it possible to not install the `libqmplay2*.a` file and get rid of `lib` prefix in libraries (see https://github.com/zaps166/QMPlay2/pull/31#issuecomment-228174930)?

> Sorry but I don't understand the which use with which.

If I understand correctly I should push the commit into your fork, right?

**Comment by arthurzam** [comment]
> specify manual linker libraries in CMake as an option

Will work on it.
> get rid of lib prefix in libraries

I think yes and not that hard.
>.. push the commit into your fork ..

Choose the easier way for you - push a commit or comment here. I think that many patches that you sent, would be much easier for you to just modify my fork.

**Comment by zaps166** [comment]
> Will work on it.

But as an option (current behavior as default) :)

**Comment by arthurzam** [comment]
I have no idea about other versions other then Qt5 5.7.0 but it works on my system :)
Also the prefix was removed (now researching if there is a better way to do it, as a global variable).

**Comment by zaps166** [comment]
Ok, you can rebase :)

> I have no idea about other versions other then Qt5 5.7.0 but it works on my system :)

Qt 5.x on Windows can use ANGLE (GLES) or desktop OpenGL depends on configuraion.

**Comment by arthurzam** [comment]
rebased (run `git pull -f` in the fork clone).
Found cleaner library prefix remove :)

**Comment by zaps166** [comment]
Ok!

Don't install `libqmplay2.dll.a`.

**Comment by zaps166** [comment]
`mingw-w64-taglib` doesn't have `pkg-config`, hmmm - so do we need to do an exception for Windows and detect taglib manually?

**Comment by zaps166** [comment]
taglib is here (append to `/etc/pacman.conf` and `sudo pacman -Syy` to sync repo):
```
[mingw-w64]
SigLevel = Optional TrustAll
Server = http://downloads.sourceforge.net/project/mingw-w64-archlinux/$arch
```

**Comment by zaps166** [comment]
`git pull -f` doesn't work, so I'll clone again

**Comment by arthurzam** [comment]
Thanks for this repository (was using `ownstuff` before).
Find taglib like gme (tried on my main system with pkg-config and with mingw version without pkg-config) - works :)

> Don't install libqmplay2.dll.a

done!

**Comment by zaps166** [comment]
Ok :) But about finding TagLib:
- TagLib (capital 'L' according to https://taglib.github.io/),
- no need to find on non-Windows OSes, just do `if` and on Windows always find, on other OSes use `pkg-config` as `REQUIRED` like before :)

**Comment by zaps166** [comment]
And I've got this:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    SHARE_INSTALL_DIR
    SYSCONF_INSTALL_DIR
```
Should we ignore it?

**Comment by arthurzam** [comment]
> no need to find on non-Windows OSes

Why not? Little code, same as with GME, therefore why not?

> And I've got this:

Yes. This is just warnings caused from the wrapper (it defines some things for installing properly on cross-compile mingw).

**Comment by zaps166** [comment]
> Why not? Little code, same as with GME, therefore why not?

GME has modification which lacks of `pkg-config` like `kode54` modification (https://github.com/kode54/Game_Music_Emu) which is better that original GME.

TagLib lacks of `pkg-config` only on Windows (also in Arch Linux package - why?). Linux, BSD and OSX uses `pkg-config` for it and also other modules needs `pkg-config`, so it won't remove the `pkg-config` dependency.

**Comment by arthurzam** [comment]
I don't try to remove the dependency. I just think that adding fallback search isn't bad. If tries at first pkg-config and if not found that try the fallback search.

**Comment by zaps166** [comment]
I thought about this:
```cmake
# Try to find TagLib, once done this will define:
#  - TAGLIB_INCLUDE_DIRS
#  - TAGLIB_LIBRARY_DIRS
#  - TAGLIB_LIBRARIES
#  - TAGLIB_FOUND

if(NOT WIN32)
    pkg_check_modules(TAGLIB taglib REQUIRED)
else()
    find_path(TAGLIB_INCLUDE_DIR taglib/taglib.h PATH_SUFFIXES taglib)
    find_library(TAGLIB_LIBRARY NAMES tag)

    include(FindPackageHandleStandardArgs)
    # handle the QUIET and REQUIRED arguments
    # set TAGLIB_FOUND to TRUE if all listed variables are TRUE
    find_package_handle_standard_args(TAGLIB DEFAULT_MSG
                                      TAGLIB_LIBRARY TAGLIB_INCLUDE_DIR)

    mark_as_advanced(TAGLIB_INCLUDE_DIR TAGLIB_LIBRARY)

    set(TAGLIB_INCLUDE_DIRS ${TAGLIB_INCLUDE_DIR})
    set(TAGLIB_LIBRARIES ${TAGLIB_LIBRARY})
endif()
```

No need to find on other platforms (or find for all other modules, but not in this PR) :)

**Comment by zaps166** [comment]
```sg
$ LC_ALL=en_US.UTF-8 make -j1
[  0%] Automatic moc for target QMPlay2
[  0%] Built target QMPlay2_automoc
[  1%] Automatic moc for target qmplay2
[  1%] Built target qmplay2_automoc
[ 16%] Built target qmplay2
[ 17%] Building CXX object src/gui/CMakeFiles/QMPlay2.dir/TagEditor.cpp.obj
/home/tomo/Desktop/QMPlay2/src/gui/TagEditor.cpp:30:21: fatal error: taglib.h: No such file or directory
compilation terminated.
make[2]: *** [src/gui/CMakeFiles/QMPlay2.dir/build.make:672: src/gui/CMakeFiles/QMPlay2.dir/TagEditor.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: src/gui/CMakeFiles/QMPlay2.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

**Comment by zaps166** [comment]
Missing definition for above comment

**Comment by zaps166** [comment]
I think that for static linking it will be enough to do something if possible:
`-DAUDIOCD_STATIC=YES -DPORTAUDIO_STATIC=YES -DTAGLIB_STATIC=YES`, etc (it should replace for static libs and use it) :)

If not possible:
`-DAUDIOCD_LIBRARIES="libcdio.a libcddb.a libwinmm.dll.a"`, etc + definition is necessary for static taglib.

**Comment by zaps166** [comment]
This works properly, I want to merge it. Let deffer static linking for Windows for next PR :) Thanks for this :)

**Comment by arthurzam** [comment]
Big thanks for those fixes and improvements and the merge :)

> Static linking

About the idea of `*_STATIC=YES`. There is some problems with this approach. pkg-config doesn't support telling the static libraries. We can try to convert the libs reported from pkg-config (cdio -> libcdio.a), but this way we don't know if this library depends on other libraries (dll file autoimports them).
Solution for this problem would be to hard set (means without an option) the libraries. I think this is a bad decision because various cross compilation system. 
My preferred solution:

- Add an `STATIC_*=YES` boolean option (only on Windows?). I will start the name with STATIC for easier grouping in cmake-gui. This option will be marked advanced.
- Another advanced option of `STATIC_*_LIBRARIES` of type string that represents the libraries. We can help the user by setting the default value (setting the default one might be problematic in case of changing options - so maybe we would design it that if the value is empty automaticly use the default one).

Instead of finding the libraries we will set as default like in the pro file.
In my idea this is the only not ugly variant. Please say your thoughts on those.

**Comment by zaps166** [comment]
One question before static linking answer: The release build is set as default, but why it is not visible in `cmake-gui`?

**Comment by zaps166** [comment]
About static: maybe something like this (uses `pkg-config` as default, user can override):
`-DPORTAUDIO_LIBRARIES="libportaudio.a libwinmm.dll.a"`
In this case `pkg-config` will not be used for libraries and `LIBPORTAUDIO_LIBRARIES` will be set to the user string. It is simple and customizable (nobody will use it, it will be convenient for me, otherwise if someone will want to use it - he/she will learn which libraries are necessary and what he/she should do) :)

**Comment by arthurzam** [comment]
> One question before static linking answer: The release build is set as default, but why it is not visible in cmake-gui?

Please check that Advanced checkbox is selected (I suggest the Grouped checkbox selected too). It should show (use the search bar).

> About static: 

I will implement it as you said. Truly the best version.

**Comment by zaps166** [comment]
> Please check that Advanced checkbox is selected (I suggest the Grouped checkbox selected too). It should show (use the search bar).

Yes, I always have advanced checked :) The `CMAKE_BUILD_TYPE` is visible, but it is empty and uses `Release` build. The same is in `SOLID_ACTION_INSTALL_PATH` - if the path is found it doesn't update it in GUI - is it possible to update it (e.g. `Qt5Core_DIR` is automatically updated)?

**Comment by zaps166** [comment]
> I will implement it as you said. Truly the best version.

Ok, thanks (I've already removed cross-compilation script from this repo)!

**Comment by zaps166** [comment]
Can't build QMPlay2 for Windows (Qt4) using CMake. QMake build works properly. This is probably after my system upgrade (now on Linux I've got Qt 5.7.0). MinGW and any windows libraries are not touched (still GCC 5.3.0).

Example output:
```bash
$ i686-w64-mingw32-cmake .. -DUSE_QT5=OFF
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'libva;libva-x11;x11'
--   No package 'libva' found
--   No package 'libva-x11' found
--   No package 'x11' found
-- Checking for modules 'vdpau;x11'
--   No package 'vdpau' found
--   No package 'x11' found
-- Checking for modules 'libcdio;libcddb'
--   Found libcdio, version 0.83
--   Found libcddb, version 1.3.2
-- Found LIBGME: /usr/i686-w64-mingw32/lib/libgme.a  
-- Checking for module 'libsidplayfp'
--   Found libsidplayfp, version 1.8.6
-- Checking for module 'libpulse-simple'
--   No package 'libpulse-simple' found
-- Checking for modules 'x11;xv'
--   No package 'x11' found
--   No package 'xv' found
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/i686-w64-mingw32/bin/qmake (found version "4.8.7") 
-- Checking for module 'libswscale>=2.5.102'
--   Found libswscale, version 4.1.100
-- Checking for module 'libavutil>=52.66.100'
--   Found libavutil, version 55.28.100
-- Checking for module 'libass'
--   Found libass, version 0.13.2
-- Checking for module 'libswresample>=0.18.100'
--   Found libswresample, version 2.1.100
-- Checking for module 'libavformat>=55.33.100'
--   Found libavformat, version 57.41.100
-- Checking for module 'libavcodec>=55.52.102'
--   Found libavcodec, version 57.48.101
-- Found ZLIB: /usr/i686-w64-mingw32/lib/libz.dll.a (found version "1.2.8") 
-- Found Qt4: /usr/i686-w64-mingw32/bin/qmake (found version "4.8.7") 
-- Found Qt4: /usr/i686-w64-mingw32/bin/qmake (found version "4.8.7") 
-- Checking for module 'portaudio-2.0'
--   Found portaudio-2.0, version 19
-- Found Qt4: /usr/i686-w64-mingw32/bin/qmake (found version "4.8.7") 
-- Found TAGLIB: /usr/i686-w64-mingw32/lib/libtag.a  
-- 
-- Enabled features:
 * ProstoPleer , Build with ProstoPleer support
 * LastFM , Build with LastFM support
 * libass , Build with libass support
 * Inputs , Build with Inputs module
 * Modplug , Build with Modplug module
 * Extensions , Build with Extensions module
 * Visualizations , Build with Visualizations module
 * AudioFilters , Build with AudioFilters module
 * VideoFilters , Build with VideoFilters module
 * OpenGL2 , Build with OpenGL2 module
 * PortAudio , Build with PortAudio module
 * TagLib , Build with tags editor
 * FFmpeg , Build with FFmpeg module
 * AudioCD , Build with AudioCD module
 * Chiptune GME , Build Chiptune with GME support
 * Chiptune SIDPLAY , Build Chiptune with SIDPLAY support

-- Disabled features:
 * CMD , Show CMD when running QMPlay2
 * Qt5 , Build with Qt5
 * libavresample , Use libavresample instead of libswresample
 * VAAPI , Build VAAPI acceleration into FFmpeg
 * VDPAU , Build VDPAU acceleration into FFmpeg
 * libavdevice , Build FFmpeg with libavdevice suport
 * ALSA , Build with ALSA module
 * PulseAudio , Build with PulseAudio module
 * XVideo , Build with XVideo module

-- Build type: Release
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    SHARE_INSTALL_DIR
    SYSCONF_INSTALL_DIR


-- Build files have been written to: /home/tomo/Dokumenty/myapps/QMPlay2/build

$ LC_ALL=en_US.UTF-8 make -j1
Scanning dependencies of target qmplay2_automoc
[  0%] Automatic moc for target qmplay2
Generating moc source moc_ColorButton.cpp
Generating moc source moc_InDockW.cpp
Generating moc source moc_LineEdit.cpp
Generating moc source moc_QMPlay2Core.cpp
Generating moc source moc_Slider.cpp
Generating moc compilation qmplay2_automoc.cpp
[  0%] Built target qmplay2_automoc
[  0%] Generating qrc_languages.cxx
/usr/i686-w64-mingw32/bin/rcc: File does not exist 'Qt4::rcc'
make[2]: *** [src/qmplay2/CMakeFiles/qmplay2.dir/build.make:64: src/qmplay2/qrc_languages.cxx] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: src/qmplay2/CMakeFiles/qmplay2.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

$ /usr/i686-w64-mingw32/bin/rcc -v
Qt Resource Compiler version 4.8.7
```

@arthurzam Any ideas? :smile:

**Comment by arthurzam** [comment]
After various testing:

1. Same happens with Qt5
2. No problem when not using cross compile.
3. The problem happens that in the generated makefiles (tested with ninja generator - same story).
4. Somehow the generated makefile has a call like `/usr/x86_64-w64-mingw32/lib/qt/bin/rcc Qt5::rcc`, thinking that `Qt5::rcc` is the filename. This `Qt5:rcc` is an variable of CMake which should be expanded before the resulting makefile.
For now I conclude that the problem originates in CMake.

---

For now I have another fix, but the problem with this fix is I don't know about support in old CMake versions. I use [AUTORCC](https://cmake.org/cmake/help/v3.6/prop_tgt/AUTORCC.html). For me it fixed the problem with qmplay2 lib (just as a start). Please check the following for older versions:

1. apply this patch [cmake-rcc.patch.txt](https://github.com/zaps166/QMPlay2/files/391864/cmake-rcc.patch.txt)
2. `cd build && i686-w64-mingw32-cmake .. -DUSE_QT5=OFF`
3. `make qmplay2 -j1`

please check that it builds (only the lib) without errors and that `Generating qrc source ...` is in the start of make output. If it work on older version, please comment it here and I will send a pull request with this patch for all other parts in QMPlay2.

**Comment by zaps166** [comment]
Is `AUTORCC` from CMake 3.0, not available in 2.8.x ?

**Comment by arthurzam** [comment]
I don't know. That why I ask. AUTOMOC (works like AUTORCC) worked on 2.8.x, but still...

**Comment by zaps166** [comment]
Aah sorry. Just tested with CMake 2.8.6 (build for Linux) - works properly with your patch :+1: Also works on `i686-w64-mingw32-cmake`, but now there is another problem: `lrelease error: Cannot open Qt4::lrelease: No such file or directory`.

**Comment by arthurzam** [comment]
Well, now it is a little funny with CMake...
Something broke with expanding the variables!
Returning to investigate.

**Comment by zaps166** [comment]
Mainly updated:
- Linux CMake 3.6.0 -> 3.6.1,
- Linux Qt 5.6.1 -> 5.7.0.

`i686-w64-mingw32-cmake` uses Linux CMake (see: `cat /usr/bin/i686-w64-mingw32-cmake`)

**Comment by zaps166** [comment]
Maybe `/usr/bin/i686-w64-mingw32-cmake` needs to be updated

**Comment by arthurzam** [comment]
I will now downgrade to cmake 3.6.0 and check it.
I don't think the problem originated in Qt, as it doesn't work also in Qt4.

**Comment by arthurzam** [comment]
Downgraded cmake to 3.6.0 - no helping - still the same error.
So I guess Qt is at fault.

**Comment by zaps166** [comment]
Linux Qt ? Because Qt on MinGW I've got the same...

**Comment by arthurzam** [comment]
I really don't know. I don't have a Windows Machine. I have only a Gentoo system (native all working) and Arch System (native works, mingw-w64 problems as explained).

Downgrading CMake to 3.6.0 didn't fix.
Downgrading Qt5 to 5.6.1 would take too long time for me.

I guess somewhere (Qt, cmake mingw-w64 wrapper, CMake itself, ...) is the problem. About compiling to Windows, after asking some friends they said: "Things break. Always keep versions of things that worked. Upgrading will be pain."

My only solution for now is to try to find version that works (like remember when you compiled successfully and watch the AUR changes to revert to those version and then compile).

Maybe asking in CMake mailing list?

**Comment by zaps166** [comment]
> Downgrading Qt5 to 5.6.1 would take too long time for me.

Qt for MinGW not touched (I've got my PKGBUILD for this).
Just removed Qt4 and Qt5 native linux and the same problem...

---

But `AUTORCC` works and it simplifies the code, so it can be done. But what about lrelease :smile: ?

**Comment by zaps166** [comment]
And the cmake wrapper is obsolete `mingw-w64-cmake`, https://sourceforge.net/projects/mingw-w64-archlinux/files/x86_64/, so not touched. Very weird :smile:

**Comment by arthurzam** [comment]
> But what about lrelease

Same bug. It doesn't expand the CMake variable (which is changed when calling `qt5_add_translation` for lrealese) which results in incorrect command call in makefile.

> Very weird
Totally agree. We haven't done anything that should fail now, after it worked before.

**Comment by zaps166** [comment]
Looks like it doesn't have defined `Qt4::lrelease` as correct file name. So the same in Qt5 for MinGW...
If `AUTORCC` works, is it a similar thing for translations?

**Comment by arthurzam** [comment]
There is AUTOUIC (which does problems that if we want to use it we must move the `*.ui` to the /src/gui folder). Therefore I don't think it is a good idea like AUTORCC.
For translations there is none.

**Comment by zaps166** [comment]
Ok, so AUTOUIC not :smile:

Currently I don't know why it doesn't work. I'll investigate later...

**Comment by zaps166** [comment]
https://github.com/Kitware/CMake/blob/master/Modules/Qt4Macros.cmake#L477

It just adds the proper path and appends "Qt4::lrelease", etc. Maybe something is wrong with in main cmake script detection? Changing `COMMAND` manually to `lrelease-qt4` in CMake script works properly...

**Comment by zaps166** [comment]
`cmake-3.5.2-Linux-x86_64` - this works properly

**Comment by zaps166** [comment]
Maybe I had 3.5.2 before :smile: So CMake bug...

**Pull request merged**
