### PR TITLE
CMake improvements (mainly for Linux and FreeBSD) - ver 2

### PR DESCRIPTION
**Pull request by arthurzam**
Continue of #24
We need to somehow push force it.
You can clone and push by force my [fork](https://github.com/arthurzam/QMPlay2).

### CODE REVIEW

**Comment by zaps166** [comment]
`git reset --soft HEAD~11` and `git push --force` :smile:

**Comment by arthurzam** [comment]
I suggest you to try this [link](http://learngitbranching.js.org/)
I learned the first time branching and all this things in git using it. Then you move to documentation.

**Comment by zaps166** [comment]
I can't push the commit which I have locally, because you're the author.
`git diff --cached`: [PR24_with_patch.txt](https://github.com/zaps166/QMPlay2/files/322416/PR24_with_patch.txt)

**Comment by arthurzam** [comment]
Can you try merge this one Pull Request?

**Comment by zaps166** [comment]
> I suggest you to try this link

Thx :D

**Comment by zaps166** [comment]
I've added bad PR number... :angry:

**Comment by arthurzam** [comment]
git commit --amend, git push -f

**Comment by zaps166** [comment]
Yes, I know :smiley:

**Comment by zaps166** [comment]
Ok, ready :)

**Comment by arthurzam** [comment]
To the next Todo List :) :)
(I'm not bored thanks to you!)

**Comment by zaps166** [comment]
Look here: da7cd85caa984bbcaeeaef655ed41243c5b309a3 - is it OK to remove sorting list (seems to be working properly)?

**Comment by zaps166** [comment]
> To the next Todo List :) :)

Hmm, Windows, OSX and Qt4+GLES ? :smile:

**Comment by arthurzam** [comment]
No!
We need it be sorted reversly - so we can check if no dir content is there and only then delete.

**Comment by zaps166** [comment]
But dirs are sorted manually, eg. first "/qmplay2/lang/", and then "/qmplay2/", hmm.

**Comment by zaps166** [comment]
Ok, I just want to know what is it :smiley: So CMake sorts using string length?

**Comment by arthurzam** [comment]
No.
list is a whole world of function that are selected by the first keyword. Here we do first regular sort and then reverse.

**Comment by zaps166** [comment]
world or word ?

**Comment by arthurzam** [comment]
[world](https://cmake.org/cmake/help/v3.0/command/list.html)

**Comment by zaps166** [comment]
Ah, Ok. Pushed commit w/o removing sorting.

**Comment by arthurzam** [comment]
okay

**Comment by zaps166** [comment]
Bugfix for FFmpeg: e335e8cee9a79b7b370221847b54e86513d8084a
For next PR:
- Some modules uses `pkg-config` for X11, some other modules gets `X11` config from CMake. All modules should do in the same way (except the root CMakeLists.txt because of message for `libxv`).
- Some modules doesn't use `link_directories` - all libraries should use it :)

**Comment by zaps166** [comment]
Thanks for the CMake :)
If you have a time you can always commit fixes :)

**Pull request merged**
