### PR TITLE
CMake cross compile static support

### PR DESCRIPTION
**Pull request by arthurzam**
As direct continuation of PR #31 and task list #22 .

Added support for static linking AudioCD, Chiptune, PortAudio, libqmplay2, gui. This consists of an advanced string option, named `STATIC_*_LIBRARIES `, which replaces the linked libraries. Checked using `-DSTATIC_PORTAUDIO_LIBRARIES="libportaudio.a libwinmm.dll.a" -DSTATIC_GUI_LIBRARIES="libtag.a libz.dll.a"`. After checking the dll dependencies (using `objdump -p <file> | grep DLL`) it is working.

Added Updater to Windows.

Default build type should be updated. About the option of solid-actions - I think is is better to not update in GUI cause empty value shows to auto detect.

### CODE REVIEW

**Comment by zaps166** [comment]
Thanks!

> Added Updater to Windows.

Ok, I forgot about this yesterday :smiley:

> Default build type should be updated. About the option of solid-actions - I think is is better to not update in GUI cause empty value shows to auto detect.

It discards the default description. Maybe don't change this (don't write the description) or re-use the default description if possible.

> STATIC_*_LIBRARIES

This allows to specify also linking to DLL's, so maybe just name it `*_LIBRARIES`? In this case add also advanced boolean option `GUI_STATIC_TAGLIB` for definition.
Maybe do it for all OS'es, not only for Win32?

**Comment by zaps166** [comment]
Also `STATIC_QMPLAY2_LIBRARIES` -> `LIBQMPLAY2_LIBRARIES` (add `LIB` prefix).

**Comment by zaps166** [comment]
Works very good, but it shows the CMD by default (missing linker flag `-Wl,-subsystem=windows` - please add advanced only for Windows `USE_CMD`, disabled by default), my command line:
```sh
i686-w64-mingw32-cmake .. -DUSE_QT5=NO -DCMAKE_INSTALL_PREFIX=~/Desktop/QW32 -DSTATIC_AUDIOCD_LIBRARIES="libcdio.a libcddb.a libregex.a libwinmm.dll.a libws2_32.dll.a" -DSTATIC_GUI_LIBRARIES="libtag.a libz.dll.a" -DSTATIC_PORTAUDIO_LIBRARIES="libportaudio.a libwinmm.dll.a" -DSTATIC_QMPLAY2_LIBRARIES="libswscale.dll.a libswresample.dll.a libavutil.dll.a libass.a libfontconfig.a libexpat.a libfreetype.a libfribidi.a libwinmm.dll.a libshell32.dll.a libpowrprof.dll.a" -DSTATIC_CHIPTUNE_LIBRARIES="libgme.a libsidplayfp.a" -DCMAKE_CXX_FLAGS_RELEASE="-O2 -DNDEBUG -fno-exceptions -g0" -DCMAKE_C_FLAGS_RELEASE="-O2 -DNDEBUG -g0"
```
```sh
make install/strip
```
:smiley:

I think that we should disable exceptions to reduce size (`-fno-exceptions`) - QMPlay2 doesn't use this. Also maybe use `-O2` by default for release build? Also why it adds `-g` for windows (maybe default CMake config from Arch Linux package?) . Maybe force `-g0` for release build as default?

**Comment by arthurzam** [comment]
> rename options to *_LIBRARIES

I'm against it because it might make problems with pkg-config finders. The pkg-config cmake module is quite advanced. It it sees this variable it will stop thinking that the results are already in cache, and that way we won't get the definitions & include libraries. Therefore I think this is better.
> advanced only for Windows USE_CMD

will add in next commit
> disable exceptions

I will add if you say so. I only want to inform you on something. Many users of QMPlay2 (like me) use the git version. As programming is unstable (maybe you will break something somewhere in code), we need to understand what happened. Without exceptions I think there would be just some global fault and a crash. Therefore I think disabling exceptions on Release (like the last one is '16.06.01') is better. Or I can add an advanced option.
> default -O2 and -g for Windows

CMake by default uses -O3 for release build. The wrapper adds the -g flag. In yours build script I suggest to not use this wrapper, and copy the cmake invocation lines, and manage them. This wrapper is quite useful, but not the best for release compilation.

**Comment by zaps166** [comment]
> I'm against it

So `CUSTOM_*_LIBRARIES` :)

**Comment by zaps166** [comment]
> Without exceptions I think there would be just some global fault and a crash.

Hmm, I think that if you want a backtrace you shouldn't strip binaries. `-fno-exception` doesn't allow you to use `try{}catch(){}` and `throw`, so it also reduces size (QMPlay2 never uses it, but Qt can use it sometimes if enabled). Maybe just read QT_CONFIG or something and use the flag which was used in Qt compilation?

**Comment by zaps166** [comment]
> CMake by default uses -O3 for release build. The wrapper adds the -g flag. In yours build script I suggest to not use this wrapper, and copy the cmake invocation lines, and manage them. This wrapper is quite useful, but not the best for release compilation.

So I'll use `-DCMAKE_C_FLAGS_RELEASE` and `-DCMAKE_CXX_FLAGS_RELEASE` :)

**Comment by arthurzam** [comment]
> about USE_CMD

After searching I found that the eight version for GCC is [-mwindows](https://gcc.gnu.org/onlinedocs/gcc-4.6.2/gcc/i386-and-x86_002d64-Windows-Options.html). Ready in the commit.
> rename to CUSTOM_*_LIBRARIES

done.
> exceptions

So, I will ad this option if clang or gcc.

**Comment by zaps166** [comment]
> So, I will ad this option if clang or gcc.

Or maybe is it possible to read the flag from qt configuration?

**Comment by arthurzam** [comment]
I have no idea how to read qt configuration from cmake. Another option is to add it to release flags.

**Comment by zaps166** [comment]
> I have no idea how to read qt configuration from cmake. Another option is to add it to release flags.

${QT_CONFIG}, works with Qt4, but not tested for Qt5 (see OpenGL2 module)

**Comment by zaps166** [comment]
Or maybe it should be in Qt5 here `${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}` or in similar variable ?

**Comment by arthurzam** [comment]
Why not make it user's responsibility ?

**Comment by zaps166** [comment]
> Why not make it user's responsibility ?

User always can use `-DCMAKE_CXX_FLAGS` to override. `qmake` uses the Qt configuration flags by default (also for exceptions).

**Comment by zaps166** [comment]
Maybe it already works for Qt5 (?) and it needs only set this in Qt4 (my Qt4 build doesn't use exceptions)?

**Comment by arthurzam** [comment]
I know that the wrapper added exceptions. Check on regular cmake invocation.

**Comment by zaps166** [comment]
`Static libs for GUI` -> `Custom libraries for GUI` - change for all modules :)

**Comment by zaps166** [comment]
`add_definitions(-DTAGLIB_STATIC)` please make it configurable by `TAGLIB_STATIC_LINK`, disabled by default (CUSTOM_* doesn't mean that this will be static) :)

**Comment by arthurzam** [comment]
changed the docstings for static libs
added -fno-exceptions for all release build (for now until we find for Qt5).
added TAGLIB_STATIC_LINK as you said.

**Comment by zaps166** [comment]
Thanks!
I'll push some commits before merge into this PR later, OK?

**Comment by zaps166** [comment]
I've reverted the "Release" build type (no need for it, it's better to have original description). I'll merge it soon :)

**Comment by zaps166** [comment]
Thanks for the PR!

**Pull request merged**
