### PR TITLE
Update installation instructions for openSUSE, add installation instructions for Fedora using RPMFusion

### PR DESCRIPTION
**Pull request by DarkWav**
So, I recently had some time so I thought it would be nice to polish the install instructions for openSUSE and update them for 15.2. I also added some instructions for Fedora 32, 31 and rawhide which use RPMFusion and include the installation of any necessary multimedia codecs.
I hope you like the new layout, any improvement suggestions are appreciated!

### CODE REVIEW

**Comment by zaps166** [comment]
Could you replace HTML tags with markdown syntax (especially `<pre>`)? It might not display properly outside GitHub. Thanks!

**Comment by DarkWav** [comment]
I will try my best, thanks for the suggestion!

**Comment by DarkWav** [comment]
OK, I switched the instructions to standard markdown. Sadly no spoilers there, but I managed to unify the Fedora instructions and removed Leap 15.1 as it will be EOL fairly soon.

**Comment by zaps166** [comment]
Thanks!

**Pull request merged**
