### PR TITLE
Fix Typos in ChangeLog

### PR DESCRIPTION
**Pull request by zo-shin**
Fix typos in ChangeLog

### CODE REVIEW

**Comment by zaps166** [comment]
hotkeys should be without space

**Comment by zo-shin** [comment]
In Oxford dictionary and Longman dictionary, the entry is separated, not one word.

**Comment by zaps166** [comment]
I think both forms are correct, but I prefer "hotkey", see:
- https://www.dictionary.com/browse/hotkey
- Zrzut ekranu_20240416_182502

**Comment by zaps166** [comment]
Thanks!

**Pull request merged**
