### PR TITLE
Simplify Strings

### PR DESCRIPTION
**Pull request by zo-shin**
simplify strings

### CODE REVIEW

**Comment by zaps166** [comment]
But there are two options which have to be used :thinking: :
Zrzut ekranu_20241227_172354

**Comment by zo-shin** [comment]
How about the new one? Or do you have any better idea?

**Comment by zaps166** [comment]
Something like this: ", you need to enable channel conversion and use it before filters option in playback settings.", but it's so hard to explain :smile:

**Comment by zaps166** [comment]
Or maybe better: ", you need to enable the channel conversion and enable option to use channel conversion before filters in playback settings." ?

**Comment by zo-shin** [comment]
quotes add

**Comment by zaps166** [comment]
Thanks!

**Pull request merged**
