### PR TITLE
Mark error logs untranslatable

### PR DESCRIPTION
**Pull request by yakushabb**
We don't need to mark error logs as translatable.

### CODE REVIEW

**Comment by zaps166** [comment]
What happened with https://github.com/zaps166/QMPlay2/pull/660 ?

**Comment by yakushabb** [comment]
It was closed automatically when I deleted my old github account.

**Comment by zaps166** [comment]
Errors displayed in status bar should be translated.

**Comment by yakushabb** [comment]
Which ones displayed in the status bar? I assumed they are just log entires.

**Comment by zaps166** [comment]
`logInfo` and `logError` has `showInGUI` argument (which is `true` by default), so most (all?) of them.

**Comment by yakushabb** [comment]
In that case, may I merge splitted sentences?

https://wiki.gnome.org/TranslationProject/DevGuidelines/Never%20split%20sentences

**Comment by zaps166** [comment]
> In that case, may I merge splitted sentences?

It requires to retranslate many sentences for all languages. But yes, try it, we'll see!

**Comment by yakushabb** [comment]
I will open another PR soon. Thanks.

**Pull request closed without merging**
